### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JesperDramsch** [matteoferla/Wikipedia_dinosaurs#1]
This is really cool. Is there a possibility you would attach an open [license](https://choosealicense.com) for reuse or sharing?

**Comment by matteoferla** [comment]
Okay. I think...
If it were data confabulated by me I'd slap the most permissive license. However it is from Wiki and their article is too long to read: [Wikipedia:Reusing_Wikipedia_content](https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content). But I see the index has CC-BY-SA. I'll use that.
Also I have no idea what the repercussions of having Jurassic Park as a field is. I am assuming none as they did not invent the dinosaurs.
If you fancy reading legalise and figure out a better one, please let me know!
